//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class OmegaEmployee
{
	public virtual void login()
	{
		throw new System.NotImplementedException();
	}

	public virtual void calculateSalary()
	{
		throw new System.NotImplementedException();
	}

}

