//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CustomerService : Employee
{
	public virtual void newCustomer()
	{
		throw new System.NotImplementedException();
	}

	public virtual void updateCustomer()
	{
		throw new System.NotImplementedException();
	}

	public virtual void deleteCustomer()
	{
		throw new System.NotImplementedException();
	}

	public virtual void searchCustomer()
	{
		throw new System.NotImplementedException();
	}

	public override void calculateSalary()
	{
		throw new System.NotImplementedException();
	}

}

