//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Employee
{
	public virtual Int empID
	{
		get;
		set;
	}

	public virtual string empFullName
	{
		get;
		set;
	}

	public virtual string address
	{
		get;
		set;
	}

	public virtual string gender
	{
		get;
		set;
	}

	public virtual Char taxCode
	{
		get;
		set;
	}

	public virtual string qualification
	{
		get;
		set;
	}

	public virtual Datetime dateOfHire
	{
		get;
		set;
	}

	public virtual Decimal hourlyWage
	{
		get;
		set;
	}

	public virtual string employmentType
	{
		get;
		set;
	}

	public virtual string password
	{
		get;
		set;
	}

	public virtual string isKiwiSaver
	{
		get;
		set;
	}

	public virtual object kiwiSaverContributionRate
	{
		get;
		set;
	}

	public virtual object IRD
	{
		get;
		set;
	}

	public virtual Float ESCTRate
	{
		get;
		set;
	}

	public virtual void login()
	{
		throw new System.NotImplementedException();
	}

	public virtual void calculateSalary()
	{
		throw new System.NotImplementedException();
	}

}

