//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HR : Employee
{
	public virtual void newEmployee()
	{
		throw new System.NotImplementedException();
	}

	public virtual void updateEmployee()
	{
		throw new System.NotImplementedException();
	}

	public virtual void deleteEmployee()
	{
		throw new System.NotImplementedException();
	}

	public virtual void searchEmployee()
	{
		throw new System.NotImplementedException();
	}

	public override void calculateSalary()
	{
		throw new System.NotImplementedException();
	}

}

